// Import the `rtkApi` from the specified location
import { rtkApi } from '@/shared/api/rtkApi';

// Import the `Notification` type from the specified location
import { Notification } from '../model/types/notification';

// Use `rtkApi.injectEndpoints` to define API endpoints for notifications
const notificationsApi = rtkApi.injectEndpoints({
  endpoints: (build) => ({
    // Define an endpoint called `getNotifications` using `build.query`
    getNotifications: build.query<Notification[], null>({
      // Define the query function for fetching notifications
      query: () => ({
        url: '/notifications',
      }),
    }),
  }),
});

// Export the `useGetNotificationsQuery` hook generated by the `notificationsApi`
export const useNotifications = notificationsApi.useGetNotificationsQuery;
